version: '3.7'

services:
  revo:
    build:
      args: 
        - UID=$UID
        - GID=$GID
      context: ./
      dockerfile: ./revo/Dockerfile
      target: development
    tty: true # docker run -t
    stdin_open: true # docker run -i
    volumes:
      - ./revo/modules/:/revo/modules
      - ./revo/notebooks/:/revo/notebooks/
    ports:
      - $JUPYTER_PORT_APP:8888
    env_file:
      - ./.env

  relationaldb:
      image: mcr.microsoft.com/mssql/server:2019-latest
      restart: always
      environment:
        - MSSQL_USER=$MSSQL_USER
        - SA_PASSWORD=$SA_PASSWORD
        - ACCEPT_EULA=Y
      ports:
        - 1433:1433
      volumes: 
        - relationaldb:/var/lib/mssql/data

volumes:
  relationaldb: