version: '3.7'

services:
  revo:
    build:
      args: 
        - UID=$UID
        - GID=$GID
      context: ./
      dockerfile: ./revo/Dockerfile
      target: development
    environment:
      - UID=$UID
      - GID=$GID
    tty: true # docker run -t
    stdin_open: true # docker run -i
    volumes:
      - ./revo/modules/:/revo/modules
      - ./revo/notebooks/:/revo/notebooks/
      - ./revo/data/:/revo/data/
      - ./revo/dimension/:/revo/dimension/
      - ./revo/data_modified/:/revo/data_modified/
      - ./revo/output/:/revo/output/
    ports:
      - $JUPYTER_PORT_APP:8888
    env_file:
      - ./.env